# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "skhantfstatesa"
    key                  = "rg/terraform.tfstate"
    resource_group_name  = "skhan-tfstate"
    storage_account_name = "skhantfstatesa"
  }
}
